class Countries {
  static Map<String, List<String>> countries = {
    "AF": ["Afghanistan", "+93", "؋"],
    "AX": ["Aland Islands", "+358", "€"],
    "AL": ["Albania", "+355", "L"],
    "DZ": ["Algeria", "+213", "د.ج."],
    "AS": ["AmericanSamoa", "+1684", "\$"],
    "AD": ["Andorra", "+376", "€"],
    "AO": ["Angola", "+244", "Kz"],
    "AI": ["Anguilla", "+1264", "\$"],
    "AQ": ["Antarctica", "+672"],
    "AG": ["Antigua and Barbuda", "+1268", "\$"],
    "AR": ["Argentina", "+54", "\$"],
    "AM": ["Armenia", "+374", "դր"],
    "AW": ["Aruba", "+297", "ƒ"],
    "AU": ["Australia", "+61", "\$"],
    "AT": ["Austria", "+43", "€"],
    "AZ": ["Azerbaijan", "+994", "₼"],
    "BS": ["Bahamas", "+1242", "\$"],
    "BH": ["Bahrain", "+973", "د.ب."],
    "BD": ["Bangladesh", "+880", "৳"],
    "BB": ["Barbados", "+1246", "\$"],
    "BY": ["Belarus", "+375"],
    "BE": ["Belgium", "+32", "€"],
    "BZ": ["Belize", "+501", "\$"],
    "BJ": ["Benin", "+229", "₣"],
    "BM": ["Bermuda", "+1441", "\$"],
    "BT": ["Bhutan", "+975", "Nu."],
    "BO": ["Bolivia, Plurinational State of", "+591", "Bs."],
    "BA": ["Bosnia and Herzegovina", "+387", "КМ"],
    "BW": ["Botswana", "+267", "P"],
    "BR": ["Brazil", "+55", "R\$"],
    "IO": ["British Indian Ocean Territory", "+246", "\$"],
    "BN": ["Brunei Darussalam", "+673", "\$"],
    "BG": ["Bulgaria", "+359", "лв."],
    "BF": ["Burkina Faso", "+226", "₣"],
    "BI": ["Burundi", "+257", "FBu"],
    "KH": ["Cambodia", "+855", "៛"],
    "CM": ["Cameroon", "+237", "Fr."],
    "CA": ["Canada", "+1", "\$"],
    "CV": ["Cape Verde", "+238", "\$"],
    "KY": ["Cayman Islands", "+ 345", "\$"],
    "CF": ["Central African Republic", "+236", "Fr."],
    "TD": ["Chad", "+235", "Fr."],
    "CL": ["Chile", "+56", "\$"],
    "CN": ["China", "+86", "¥元"],
    "CX": ["Christmas Island", "+61", "\$"],
    "CC": ["Cocos (Keeling) Islands", "+61", "\$"],
    "CO": ["Colombia", "+57", "\$"],
    "KM": ["Comoros", "+269", "CF"],
    "CG": ["Congo", "+242", "Fr."],
    "CD": ["Congo, The Democratic Republic of the Congo", "+243", "₣"],
    "CK": ["Cook Islands", "+682", "\$"],
    "CR": ["Costa Rica", "+506", "₡"],
    "CI": ["Cote d'Ivoire", "+225", "₣"],
    "HR": ["Croatia", "+385", "kn"],
    "CU": ["Cuba", "+53", "₱"],
    "CY": ["Cyprus", "+357", "€"],
    "CZ": ["Czech Republic", "+420", "Kč"],
    "DK": ["Denmark", "+45", "kr."],
    "DJ": ["Djibouti", "+253", "ف.ج."],
    "DM": ["Dominica", "+1767", "\$"],
    "DO": ["Dominican Republic", "+1849", "\$"],
    "EC": ["Ecuador", "+593", "\$"],
    "EG": ["Egypt", "+20", "ج.م."],
    "SV": ["El Salvador", "+503", "\$"],
    "GQ": ["Equatorial Guinea", "+240", "Fr."],
    "ER": ["Eritrea", "+291", "ناكفا"],
    "EE": ["Estonia", "+372", "€"],
    "ET": ["Ethiopia", "+251", "ብር"],
    "FK": ["Falkland Islands (Malvinas)", "+500", "£"],
    "FO": ["Faroe Islands", "+298", "kr."],
    "FJ": ["Fiji", "+679", "\$"],
    "FI": ["Finland", "+358", "€"],
    "FR": ["France", "+33", "€"],
    "GF": ["French Guiana", "+594", "€"],
    "PF": ["French Polynesia", "+689", "₣"],
    "GA": ["Gabon", "+241", "Fr."],
    "GM": ["Gambia", "+220", "D"],
    "GE": ["Georgia", "+995", "₾"],
    "DE": ["Germany", "+49", "€"],
    "GH": ["Ghana", "+233", "₵"],
    "GI": ["Gibraltar", "+350", "£"],
    "GR": ["Greece", "+30", "€"],
    "GL": ["Greenland", "+299", "kr."],
    "GD": ["Grenada", "+1473", "\$"],
    "GP": ["Guadeloupe", "+590", "€"],
    "GU": ["Guam", "+1671", "\$"],
    "GT": ["Guatemala", "+502", "\$"],
    "GG": ["Guernsey", "+44", "£"],
    "GN": ["Guinea", "+224", "FG"],
    "GW": ["Guinea-Bissau", "+245", "₣"],
    "GY": ["Guyana", "+595", "\$"],
    "HT": ["Haiti", "+509", "G"],
    "VA": ["Holy See (Vatican City State)", "+379", "€"],
    "HN": ["Honduras", "+504", "L"],
    "HK": ["Hong Kong", "+852", "\$"],
    "HU": ["Hungary", "+36", "Ft"],
    "IS": ["Iceland", "+354", "kr"],
    "IN": ["India", "+91", "₹"],
    "ID": ["Indonesia", "+62", "Rp"],
    "IR": ["Iran, Islamic Republic of Persian Gulf", "+98", "﷼"],
    "IQ": ["Iraq", "+964", "د.ع."],
    "IE": ["Ireland", "+353", "€"],
    "IM": ["Isle of Man", "+44", "£"],
    "IL": ["Israel", "+972", "₪"],
    "IT": ["Italy", "+39", "€"],
    "JM": ["Jamaica", "+1876", "\$"],
    "JP": ["Japan", "+81", "¥"],
    "JE": ["Jersey", "+44", "£"],
    "JO": ["Jordan", "+962", "د.أ."],
    "KZ": ["Kazakhstan", "+77", "₸"],
    "KE": ["Kenya", "+254", "KSh"],
    "KI": ["Kiribati", "+686", "\$"],
    "KP": ["Korea, Democratic People's Republic of Korea", "+850", "₩"],
    "KR": ["Korea, Republic of South Korea", "+82", "₩"],
    "KW": ["Kuwait", "+965", "د.ك."],
    "KG": ["Kyrgyzstan", "+996", "с"],
    "LA": ["Laos", "+856", "₭"],
    "LV": ["Latvia", "+371", "€"],
    "LB": ["Lebanon", "+961", "ل.ل."],
    "LS": ["Lesotho", "+266", "L"],
    "LR": ["Liberia", "+231", "\$"],
    "LY": ["Libyan Arab Jamahiriya", "+218", "ل.د."],
    "LI": ["Liechtenstein", "+423", "₣"],
    "LT": ["Lithuania", "+370"],
    "LU": ["Luxembourg", "+352", "€"],
    "MO": ["Macao", "+853", "MOP\$"],
    "MK": ["Macedonia", "+389", "ден"],
    "MG": ["Madagascar", "+261", "Ar"],
    "MW": ["Malawi", "+265", "MK"],
    "MY": ["Malaysia", "+60", "RM"],
    "MV": ["Maldives", "+960", ".ރ"],
    "ML": ["Mali", "+223", "₣"],
    "MT": ["Malta", "+356", "€"],
    "MH": ["Marshall Islands", "+692", "\$"],
    "MQ": ["Martinique", "+596", "€"],
    "MR": ["Mauritania", "+222"],
    "MU": ["Mauritius", "+230", "रु "],
    "YT": ["Mayotte", "+262", "€"],
    "MX": ["Mexico", "+52", "\$"],
    "FM": ["Micronesia, Federated States of Micronesia", "+691", "\$"],
    "MD": ["Moldova", "+373", "L"],
    "MC": ["Monaco", "+377", "€"],
    "MN": ["Mongolia", "+976", "₮"],
    "ME": ["Montenegro", "+382", "€"],
    "MS": ["Montserrat", "+1664", "\$"],
    "MA": ["Morocco", "+212", "د.م."],
    "MZ": ["Mozambique", "+258", "MT"],
    "MM": ["Myanmar", "+95", "Ks"],
    "NA": ["Namibia", "+264", "\$"],
    "NR": ["Nauru", "+674", "\$"],
    "NP": ["Nepal", "+977", "रू"],
    "NL": ["Netherlands", "+31", "€"],
    "AN": ["Netherlands Antilles", "+599"],
    "NC": ["New Caledonia", "+687", "₣"],
    "NZ": ["New Zealand", "+64", "\$"],
    "NI": ["Nicaragua", "+505", "C\$"],
    "NE": ["Niger", "+227", "₣"],
    "NG": ["Nigeria", "+234", "₦"],
    "NU": ["Niue", "+683", "\$"],
    "NF": ["Norfolk Island", "+672", "\$"],
    "MP": ["Northern Mariana Islands", "+1670", "\$"],
    "NO": ["Norway", "+47", "kr"],
    "OM": ["Oman", "+968", "ر.ع."],
    "PK": ["Pakistan", "+92", "Rs"],
    "PW": ["Palau", "+680", "\$"],
    "PS": ["Palestinian Territory, Occupied", "+970", "₪"],
    "PA": ["Panama", "+507", "B/."],
    "PG": ["Papua New Guinea", "+675", "K"],
    "PY": ["Paraguay", "+595", "₲"],
    "PE": ["Peru", "+51", "S/."],
    "PH": ["Philippines", "+63", "₱"],
    "PN": ["Pitcairn", "+872", "\$"],
    "PL": ["Poland", "+48", "zł"],
    "PT": ["Portugal", "+351", "€"],
    "PR": ["Puerto Rico", "+1939", "\$"],
    "QA": ["Qatar", "+974", "ر.ق."],
    "RO": ["Romania", "+40", "L"],
    "RU": ["Russia", "+7", "₽"],
    "RW": ["Rwanda", "+250", "R₣"],
    "RE": ["Reunion", "+262", "€"],
    "BL": ["Saint Barthelemy", "+590", "€"],
    "SH": ["Saint Helena, Ascension and Tristan Da Cunha", "+290", "£"],
    "KN": ["Saint Kitts and Nevis", "+1869", "\$"],
    "LC": ["Saint Lucia", "+1758", "\$"],
    "MF": ["Saint Martin", "+590", "€"],
    "PM": ["Saint Pierre and Miquelon", "+508", "€"],
    "VC": ["Saint Vincent and the Grenadines", "+1784", "\$"],
    "WS": ["Samoa", "+685", "ST"],
    "SM": ["San Marino", "+378", "€"],
    "ST": ["Sao Tome and Principe", "+239"],
    "SA": ["Saudi Arabia", "+966", "ر.س."],
    "SN": ["Senegal", "+221", "₣"],
    "RS": ["Serbia", "+381", "дин"],
    "SC": ["Seychelles", "+248", "Rs"],
    "SL": ["Sierra Leone", "+232", "Le"],
    "SG": ["Singapore", "+65", "\$"],
    "SK": ["Slovakia", "+421", "€"],
    "SI": ["Slovenia", "+386", "€"],
    "SB": ["Solomon Islands", "+677", "\$"],
    "SO": ["Somalia", "+252", "Ssh"],
    "ZA": ["South Africa", "+27", "R"],
    "SS": ["South Sudan", "+211", "SS£"],
    "GS": ["South Georgia and the South Sandwich Islands", "+500", "£"],
    "ES": ["Spain", "+34", "€"],
    "LK": ["Sri Lanka", "+94", "රු or ரூ"],
    "SD": ["Sudan", "+249", "ج.س."],
    "SR": ["Suriname", "+597", "\$"],
    "SJ": ["Svalbard and Jan Mayen", "+47", "kr"],
    "SZ": ["Swaziland", "+268", "L"],
    "SE": ["Sweden", "+46", "kr"],
    "CH": ["Switzerland", "+41", "₣"],
    "SY": ["Syrian Arab Republic", "+963", "ل.س."],
    "TW": ["Taiwan", "+886", "圓"],
    "TJ": ["Tajikistan", "+992", "SM"],
    "TZ": ["Tanzania, United Republic of Tanzania", "+255", "TSh"],
    "TH": ["Thailand", "+66", "฿"],
    "TL": ["Timor-Leste", "+670", "\$"],
    "TG": ["Togo", "+228", "₣"],
    "TK": ["Tokelau", "+690", "\$"],
    "TO": ["Tonga", "+676", "PT"],
    "TT": ["Trinidad and Tobago", "+1868", "\$"],
    "TN": ["Tunisia", "+216", "د.ت."],
    "TR": ["Turkey", "+90", "₺"],
    "TM": ["Turkmenistan", "+993", "T"],
    "TC": ["Turks and Caicos Islands", "+1649", "\$"],
    "TV": ["Tuvalu", "+688", "\$"],
    "UG": ["Uganda", "+256", "Sh"],
    "UA": ["Ukraine", "+380", "грн"],
    "AE": ["United Arab Emirates", "+971", "د.إ."],
    "GB": ["United Kingdom", "+44", "£"],
    "US": ["United States", "+1", "\$"],
    "UY": ["Uruguay", "+598", "\$"],
    "UZ": ["Uzbekistan", "+998", "сум"],
    "VN": ["Vietnam", "+84", "₫"],
    "ZW": ["Zimbabwe", "+263", "\$"]
  };
}
