// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZHfXwZJGPjJMj1vZwD7nUXHQLtgfCjHs',
    appId: '1:854432405074:android:c9bad2b28e657803b2718b',
    messagingSenderId: '854432405074',
    projectId: 'mytiffincrm',
    storageBucket: 'mytiffincrm.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsQSBbURlW0VPFILIk7sg_mNB1vkICjB8',
    appId: '1:854432405074:web:e25fe3b13dbc5d37b2718b',
    messagingSenderId: '854432405074',
    projectId: 'mytiffincrm',
    authDomain: 'mytiffincrm.firebaseapp.com',
    storageBucket: 'mytiffincrm.appspot.com',
    measurementId: 'G-MTD9G2QXEH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBtqBdlvJkSqgFqTktVNtE0uR8kKszWHo',
    appId: '1:854432405074:ios:1d1fa05e72333252b2718b',
    messagingSenderId: '854432405074',
    projectId: 'mytiffincrm',
    storageBucket: 'mytiffincrm.appspot.com',
    iosBundleId: 'com.example.deliveryManagement',
  );

}